version: '3'
services:
  php-fpm:
    container_name: php_kaitohealth
    build: ./.docker/php
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql_kaitohealth
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_kaitohealth
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    links:
      - php-fpm

networks:
  laravel:
    driver: bridge
