version: '3.3'
services:
  php-fpm:
    container_name: php_kaitohealth
    build: ./.docker/php
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql_kaitohealth
    restart: unless-stopped
    tty: true
    secrets:
      - dbu
      - dbpw
    environment:
      MYSQL_DATABASE: basic
      MYSQL_USER: /run/secrets/dbu
      MYSQL_PASSWORD: /run/secrets/dbpw
      MYSQL_ROOT_PASSWORD: /run/secrets/dbpw
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_kaitohealth
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    links:
      - php-fpm

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local

secrets:
  dbu:
    file: ./.docker/secrets/dbu.txt
  dbpw:
    file: ./.docker/secrets/dbpw.txt
